name: Build dummy dependency

on:
  workflow_dispatch:
    secrets:
      DEPLOY_GITHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - run: echo "'${{ secrets.DEPLOY_GITHUB_TOKEN }}'"

    - name: Build with Maven
      run: mvn -B -P github deploy --file dummy-dependency/pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
