name: Test current branch

on: [push, workflow_call, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ github.token }}

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - uses: s4u/maven-settings-action@v3.0.0
      with:
        githubServer: false # avoid conflict with "github" serve below
        servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ github.token }}"}]'

    - name: Run action (non-branch version)
      id: run-action-non-branch-version
      uses: maven-flow/manage-versions@main
      with:
        enforce-branch-version: true
        maven-args: "-P github"
        pom-file: "non-branch-version-pom.xml"

    - name: Assert version unchanged
      run: .github/workflows/assert-project-version.sh non-branch-version-pom.xml 1.0.0

    - name: Assert dependency version unchanged
      run: .github/workflows/assert-dependency-version.sh non-branch-version-pom.xml com.jardoapps.maven-flow dummy-dependency 1.0.0

    - name: Run action (branch version)
      id: run-action-branch-version
      uses: maven-flow/manage-versions@main
      with:
        enforce-branch-version: true
        maven-args: "-P github"
        pom-file: "branch-version-pom.xml"

    - name: Assert version changed
      run: .github/workflows/assert-project-version.sh branch-version-pom.xml 1.0.1-SNAPSHOT

    - name: Assert dependency version changed
      run: .github/workflows/assert-dependency-version.sh branch-version-pom.xml com.jardoapps.maven-flow dummy-dependency 1.0.1-SNAPSHOT
