name: Test current branch

on: [workflow_call, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

      - id: run-action
        uses: maven-flow/manage-versions@main
